name: build blog nextjs webapp
on: push
jobs:
    build-project:
    name: build project
    runs-on: ubuntu-latest
    steps:
        - name: checkout code
        uses: actions/checkout@v3
        - name: install npm dependencies
        run: npm install
        - name: build project assets
        run: npm run build
